---
repos:
   -  repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-toml
      -   id: check-json
      -   id: check-added-large-files
      -   id: check-merge-conflict
      -   id: check-symlinks
      -   id: debug-statements
      -   id: detect-private-key
      -   id: mixed-line-ending
   - repo: https://github.com/JohnnyMorganz/StyLua
     rev: v0.18.2
     hooks:
       - id: stylua # or stylua-system / stylua-github
         # args: [ --quote-style, AutoPreferDouble, --call-parentheses, Always]
         args:
           - --quote-style
           - ForceDouble
           - --call-parentheses
           - Always
           - --indent-type
           - Spaces
           - --indent-width
           - "2"
