# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, post-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-d, relaxed]
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.19.1
    hooks:
      - id: stylua # or stylua-system / stylua-github
        args:
          - --quote-style
          - ForceDouble
          - --call-parentheses
          - Always
          - --indent-type
          - Spaces
          - --indent-width
          - "2"
  - repo: local
    hooks:
      - id: git-cliff
        name: git-cliff
        language: system
        entry: git-cliff
        require_serial: true
        stages: [post-commit]
