#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


alias ls="exa"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/hicham/.miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/hicham/.miniconda/etc/profile.d/conda.sh" ]; then
        . "/home/hicham/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/hicham/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<



[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.git-extras-completion.zsh
