[data]
name = "{{ (gh auth status --show-token | grep -oP '(?<=Logged in to github.com as )\\S+') }}"
email = "{{ (gh api user | jq -r '.email') }}"

[diff]
command = "/opt/homebrew/bin/difft"
args = ["--display=inline", "--color=always", "{{.Destination}}", "{{.Target}}"]

[merge]
command = "nvim"
args = ["-f", "-c", "Gvdiffsplit! {{.Destination}} {{.Target}}", "{{.Source}}"]
